name = "grounded"
main = "src/app.js"
compatibility_date = "2024-10-15"
account_id = "1f14287e8693599be17bb11f84ad5921"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "grounded-db"
database_id = "58597121-3567-4e9a-90f6-0b15a2a12b8e"

# Environment Variables
[vars]
ENVIRONMENT = "development"
CLAUDE_MODEL = "claude-3-5-sonnet-20241022"

# For production deployment
[env.production]
vars = { ENVIRONMENT = "production", CLAUDE_MODEL = "claude-3-5-sonnet-20241022" }

# Note: ANTHROPIC_API_KEY should be set in Cloudflare Pages dashboard
# as a secret environment variable for security

# KV Namespaces (for caching if needed later)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
